# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Image(Model):
    """The image update trigger that caused a build.

    :param registry: The registry from which the image is updated.
    :type registry: str
    :param repository: The repository name of the updated image.
    :type repository: str
    :param tag: The tag name of the updated image.
    :type tag: str
    :param digest: The digest of the updated image manifest.
    :type digest: str
    :param size: The size of the updated image.
    :type size: long
    """

    _attribute_map = {
        'registry': {'key': 'registry', 'type': 'str'},
        'repository': {'key': 'repository', 'type': 'str'},
        'tag': {'key': 'tag', 'type': 'str'},
        'digest': {'key': 'digest', 'type': 'str'},
        'size': {'key': 'size', 'type': 'long'},
    }

    def __init__(self, registry=None, repository=None, tag=None, digest=None, size=None):
        super(Image, self).__init__()
        self.registry = registry
        self.repository = repository
        self.tag = tag
        self.digest = digest
        self.size = size
