# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .container_registry import ContainerRegistry, ContainerRegistryConfiguration
from .version import VERSION

__all__ = [
    'ContainerRegistry',
    'ContainerRegistryConfiguration'
]

__version__ = VERSION

