# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .registry_name_check_request import RegistryNameCheckRequest
from .registry_name_status import RegistryNameStatus
from .operation_display_definition import OperationDisplayDefinition
from .operation_definition import OperationDefinition
from .sku import Sku
from .status import Status
from .storage_account_properties import StorageAccountProperties
from .registry import Registry
from .registry_update_parameters import RegistryUpdateParameters
from .registry_password import RegistryPassword
from .registry_list_credentials_result import RegistryListCredentialsResult
from .regenerate_credential_parameters import RegenerateCredentialParameters
from .registry_usage import RegistryUsage
from .registry_usage_list_result import RegistryUsageListResult
from .replication import Replication
from .replication_update_parameters import ReplicationUpdateParameters
from .webhook import Webhook
from .webhook_create_parameters import WebhookCreateParameters
from .webhook_update_parameters import WebhookUpdateParameters
from .event_info import EventInfo
from .callback_config import CallbackConfig
from .target import Target
from .request import Request
from .actor import Actor
from .source import Source
from .event_content import EventContent
from .event_request_message import EventRequestMessage
from .event_response_message import EventResponseMessage
from .event import Event
from .resource import Resource
from .image_descriptor import ImageDescriptor
from .image_update_trigger import ImageUpdateTrigger
from .git_commit_trigger import GitCommitTrigger
from .platform_properties import PlatformProperties
from .build import Build
from .build_filter import BuildFilter
from .build_update_parameters import BuildUpdateParameters
from .build_get_log_result import BuildGetLogResult
from .build_step_properties import BuildStepProperties
from .build_step import BuildStep
from .build_step_properties_update_parameters import BuildStepPropertiesUpdateParameters
from .build_step_update_parameters import BuildStepUpdateParameters
from .build_argument import BuildArgument
from .source_control_auth_info import SourceControlAuthInfo
from .source_repository_properties import SourceRepositoryProperties
from .build_task import BuildTask
from .build_task_filter import BuildTaskFilter
from .source_repository_update_parameters import SourceRepositoryUpdateParameters
from .build_task_update_parameters import BuildTaskUpdateParameters
from .queue_build_request import QueueBuildRequest
from .source_upload_definition import SourceUploadDefinition
from .proxy_resource import ProxyResource
from .error import Error
from .error_response import ErrorResponse
from .base_image_dependency import BaseImageDependency
from .docker_build_step import DockerBuildStep
from .docker_build_step_update_parameters import DockerBuildStepUpdateParameters
from .build_task_build_request import BuildTaskBuildRequest
from .quick_build_request import QuickBuildRequest
from .registry_paged import RegistryPaged
from .operation_definition_paged import OperationDefinitionPaged
from .replication_paged import ReplicationPaged
from .webhook_paged import WebhookPaged
from .event_paged import EventPaged
from .build_paged import BuildPaged
from .build_step_paged import BuildStepPaged
from .build_argument_paged import BuildArgumentPaged
from .build_task_paged import BuildTaskPaged
from .container_registry_management_client_enums import (
    SkuName,
    SkuTier,
    ProvisioningState,
    PasswordName,
    RegistryUsageUnit,
    WebhookStatus,
    WebhookAction,
    BuildStatus,
    BuildType,
    OsType,
    BuildTaskStatus,
    SourceControlType,
    TokenType,
    BaseImageDependencyType,
    BaseImageTriggerType,
)

__all__ = [
    'RegistryNameCheckRequest',
    'RegistryNameStatus',
    'OperationDisplayDefinition',
    'OperationDefinition',
    'Sku',
    'Status',
    'StorageAccountProperties',
    'Registry',
    'RegistryUpdateParameters',
    'RegistryPassword',
    'RegistryListCredentialsResult',
    'RegenerateCredentialParameters',
    'RegistryUsage',
    'RegistryUsageListResult',
    'Replication',
    'ReplicationUpdateParameters',
    'Webhook',
    'WebhookCreateParameters',
    'WebhookUpdateParameters',
    'EventInfo',
    'CallbackConfig',
    'Target',
    'Request',
    'Actor',
    'Source',
    'EventContent',
    'EventRequestMessage',
    'EventResponseMessage',
    'Event',
    'Resource',
    'ImageDescriptor',
    'ImageUpdateTrigger',
    'GitCommitTrigger',
    'PlatformProperties',
    'Build',
    'BuildFilter',
    'BuildUpdateParameters',
    'BuildGetLogResult',
    'BuildStepProperties',
    'BuildStep',
    'BuildStepPropertiesUpdateParameters',
    'BuildStepUpdateParameters',
    'BuildArgument',
    'SourceControlAuthInfo',
    'SourceRepositoryProperties',
    'BuildTask',
    'BuildTaskFilter',
    'SourceRepositoryUpdateParameters',
    'BuildTaskUpdateParameters',
    'QueueBuildRequest',
    'SourceUploadDefinition',
    'ProxyResource',
    'Error',
    'ErrorResponse',
    'BaseImageDependency',
    'DockerBuildStep',
    'DockerBuildStepUpdateParameters',
    'BuildTaskBuildRequest',
    'QuickBuildRequest',
    'RegistryPaged',
    'OperationDefinitionPaged',
    'ReplicationPaged',
    'WebhookPaged',
    'EventPaged',
    'BuildPaged',
    'BuildStepPaged',
    'BuildArgumentPaged',
    'BuildTaskPaged',
    'SkuName',
    'SkuTier',
    'ProvisioningState',
    'PasswordName',
    'RegistryUsageUnit',
    'WebhookStatus',
    'WebhookAction',
    'BuildStatus',
    'BuildType',
    'OsType',
    'BuildTaskStatus',
    'SourceControlType',
    'TokenType',
    'BaseImageDependencyType',
    'BaseImageTriggerType',
]
