# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegistryPropertiesCreateParameters(Model):
    """RegistryPropertiesCreateParameters

    :param tenant_id:
    :type tenant_id: str
    :param storage_account:
    :type storage_account: :class:`StorageAccountProperties
     <containerregistry.models.StorageAccountProperties>`
    """ 

    _attribute_map = {
        'tenant_id': {'key': 'tenantId', 'type': 'str'},
        'storage_account': {'key': 'storageAccount', 'type': 'StorageAccountProperties'},
    }

    def __init__(self, tenant_id=None, storage_account=None):
        self.tenant_id = tenant_id
        self.storage_account = storage_account
