# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegistryUpdateParameters(Model):
    """RegistryUpdateParameters

    :param tags:
    :type tags: dict
    :param properties:
    :type properties: :class:`RegistryPropertiesCreateParameters
     <containerregistry.models.RegistryPropertiesCreateParameters>`
    """ 

    _attribute_map = {
        'tags': {'key': 'tags', 'type': '{str}'},
        'properties': {'key': 'properties', 'type': 'RegistryPropertiesCreateParameters'},
    }

    def __init__(self, tags=None, properties=None):
        self.tags = tags
        self.properties = properties
