#---------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#---------------------------------------------------------------------------------------------
#pylint: skip-file
# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RegistryProperties(Model):
    """RegistryProperties

    :param storage_account:
    :type storage_account: :class:`StorageAccountProperties
     <containerregistry.models.StorageAccountProperties>`
    :param login_server:
    :type login_server: str
    :param username:
    :type username: str
    :param key:
    :type key: str
    :param creation_date:
    :type creation_date: datetime
    """ 

    _attribute_map = {
        'storage_account': {'key': 'storageAccount', 'type': 'StorageAccountProperties'},
        'login_server': {'key': 'loginServer', 'type': 'str'},
        'username': {'key': 'username', 'type': 'str'},
        'key': {'key': 'key', 'type': 'str'},
        'creation_date': {'key': 'creationDate', 'type': 'iso-8601'},
    }

    def __init__(self, storage_account=None, login_server=None, username=None, key=None, creation_date=None):
        self.storage_account = storage_account
        self.login_server = login_server
        self.username = username
        self.key = key
        self.creation_date = creation_date
