#---------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#---------------------------------------------------------------------------------------------
#pylint: skip-file
# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ResourceListRegistryParameters(Model):
    """ResourceListRegistryParameters

    :param value:
    :type value: list of :class:`RegistryParameters
     <containerregistry.models.RegistryParameters>`
    """ 

    _attribute_map = {
        'value': {'key': 'value', 'type': '[RegistryParameters]'},
    }

    def __init__(self, value=None):
        self.value = value
