#---------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#---------------------------------------------------------------------------------------------
#pylint: skip-file
# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class StorageAccountProperties(Model):
    """StorageAccountProperties

    :param name:
    :type name: str
    :param access_key:
    :type access_key: str
    :param end_point_url:
    :type end_point_url: str
    :param endpoint_suffix:
    :type endpoint_suffix: str
    """ 

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'access_key': {'key': 'accessKey', 'type': 'str'},
        'end_point_url': {'key': 'endPointUrl', 'type': 'str'},
        'endpoint_suffix': {'key': 'endpointSuffix', 'type': 'str'},
    }

    def __init__(self, name=None, access_key=None, end_point_url=None, endpoint_suffix=None):
        self.name = name
        self.access_key = access_key
        self.end_point_url = end_point_url
        self.endpoint_suffix = endpoint_suffix
