# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class SkuName(Enum):

    basic = "Basic"
    standard_small = "Standard_Small"
    standard_medium = "Standard_Medium"
    standard_large = "Standard_Large"


class SkuTier(Enum):

    basic = "Basic"
    standard = "Standard"


class ProvisioningState(Enum):

    creating = "Creating"
    succeeded = "Succeeded"


class PasswordName(Enum):

    password = "password"
    password2 = "password2"


class WebhookAction(Enum):

    push = "push"
    pull = "pull"
    delete = "delete"
