# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class WebhookCreateParameters(Model):
    """The parameters for creating a webhook.

    :param tags: The tags for the webhook.
    :type tags: dict
    :param location: The location of the webhook. This cannot be changed after
     the resource is created.
    :type location: str
    :param service_uri: The service URI for the webhook to post notifications.
    :type service_uri: str
    :param custom_headers: Custom headers that will be added to the webhook
     notifications.
    :type custom_headers: dict
    :param is_enabled: The value that indicates whether the webhook is
     enabled. Default value: True .
    :type is_enabled: bool
    :param scope: The scope of repositories where the event can be triggered.
    :type scope: str
    :param actions: The list of actions that trigger the webhook to post
     notifications.
    :type actions: list of str or :class:`WebhookAction
     <azure.mgmt.containerregistry.models.WebhookAction>`
    """

    _validation = {
        'location': {'required': True},
        'service_uri': {'required': True},
        'actions': {'required': True},
    }

    _attribute_map = {
        'tags': {'key': 'tags', 'type': '{str}'},
        'location': {'key': 'location', 'type': 'str'},
        'service_uri': {'key': 'properties.serviceUri', 'type': 'str'},
        'custom_headers': {'key': 'properties.customHeaders', 'type': '{str}'},
        'is_enabled': {'key': 'properties.isEnabled', 'type': 'bool'},
        'scope': {'key': 'properties.scope', 'type': 'str'},
        'actions': {'key': 'properties.actions', 'type': '[str]'},
    }

    def __init__(self, location, service_uri, actions, tags=None, custom_headers=None, is_enabled=True, scope=None):
        self.tags = tags
        self.location = location
        self.service_uri = service_uri
        self.custom_headers = custom_headers
        self.is_enabled = is_enabled
        self.scope = scope
        self.actions = actions
